
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
  instance:
    hostname: localhost

#server:
#  port: 6001

spring:
  application:
    name: user
  profiles:
    active: peer2
